### ISSUE TITLE
footer.scss and header.scss are clones of menu.scss

### ISSUE THREAD

**Issue by callan-stretton** [PlasticStudio/skeletor#20]
app/scss/components/_footer.scss

**Comment by callan-stretton** [comment]
app/scss/components/_footer.scss
app/scss/components/_header.scss
app/scss/components/_menu.scss

**Comment by jareddreyer** [comment]
@jaedb  this was by design for ease of update right?

**Comment by jareddreyer** [comment]
@callan-stretton This was by design doesn't need to be changed/deleted etc.
